export const categories = [
  { slug: "cleanser", name: "Cleanser" },
  { slug: "toner", name: "Toner" },
  { slug: "serum", name: "Serum" },
  { slug: "moisturizer", name: "Moisturizer" },
  { slug: "sunscreen", name: "Sunscreen" },
]

export const products = [
  {
    slug: "gentle-gel-cleanser",
    name: "Gentle Gel Cleanser",
    category: "cleanser",
    categoryLabel: "Cleanser",
    price: 69000,
    image: "/cleanser-gentle-gel.jpg",
    tags: ["Glycerin", "Panthenol"],
    suitableSkinTypes: ["kering", "normal", "kombinasi", "berminyak"],
    benefits: ["Membersihkan tanpa membuat kering", "Menjaga skin barrier"],
  },
  {
    slug: "soothing-toner",
    name: "Soothing Toner",
    category: "toner",
    categoryLabel: "Toner",
    price: 79000,
    image: "/soothing-toner.jpg",
    tags: ["Centella", "Allantoin"],
    suitableSkinTypes: ["kering", "normal", "kombinasi"],
    benefits: ["Menenangkan kulit", "Menghidrasi"],
  },
  {
    slug: "niacinamide-serum-10",
    name: "Niacinamide Serum 10%",
    category: "serum",
    categoryLabel: "Serum",
    price: 119000,
    image: "/niacinamide-serum.jpg",
    tags: ["Niacinamide", "Zinc"],
    suitableSkinTypes: ["normal", "kombinasi", "berminyak"],
    benefits: ["Mencerahkan", "Mengontrol sebum"],
  },
  {
    slug: "hyaluronic-boost-serum",
    name: "Hyaluronic Boost Serum",
    category: "serum",
    categoryLabel: "Serum",
    price: 129000,
    image: "/hyaluronic-acid-serum.jpg",
    tags: ["Hyaluronic Acid", "Glycerin"],
    suitableSkinTypes: ["kering", "normal", "kombinasi"],
    benefits: ["Hidrasi intens", "Kulit lebih plump"],
  },
  {
    slug: "ceramide-moist-cream",
    name: "Ceramide Moist Cream",
    category: "moisturizer",
    categoryLabel: "Moisturizer",
    price: 99000,
    image: "/ceramide-cream.png",
    tags: ["Ceramide", "Squalane"],
    suitableSkinTypes: ["kering", "normal"],
    benefits: ["Menguatkan skin barrier", "Melembapkan"],
  },
  {
    slug: "daily-sun-fluid-spf50",
    name: "Daily Sun Fluid SPF50",
    category: "sunscreen",
    categoryLabel: "Sunscreen",
    price: 109000,
    image: "/sunscreen-spf50.png",
    tags: ["UVA/UVB Filter", "Vitamin E"],
    suitableSkinTypes: ["normal", "kombinasi", "berminyak"],
    benefits: ["Perlindungan harian", "Ringan & tidak lengket"],
  },
  {
    slug: "dummy-serum",
    name: "Dummy Serum Glow",
    category: "serum",
    categoryLabel: "Serum",
    price: 89000,
    image: "/serum-dummy-bottle.jpg",
    tags: ["Niacinamide", "Hyaluronic Acid"],
    suitableSkinTypes: ["kering", "normal", "kombinasi", "berminyak"],
    benefits: ["Contoh produk untuk demo", "Menunjukkan halaman detail produk"],
  },
  {
    slug: "glow-bright-serum",
    name: "Glow Bright Serum",
    brand: "Glow",
    category: "serum",
    categoryLabel: "Serum",
    price: 139000,
    image: "/glow-brightening-serum-bottle-on-white.jpg",
    tags: ["Niacinamide", "Vitamin C"],
    suitableSkinTypes: ["normal", "kombinasi", "berminyak"],
    benefits: ["Mencerahkan", "Menyamarkan noda"],
  },
  {
    slug: "glow-soft-cleanser",
    name: "Glow Soft Cleanser",
    brand: "Glow",
    category: "cleanser",
    categoryLabel: "Cleanser",
    price: 79000,
    image: "/gentle-facial-cleanser-tube-minimal.jpg",
    tags: ["Glycerin", "Panthenol"],
    suitableSkinTypes: ["kering", "normal", "kombinasi"],
    benefits: ["Membersihkan lembut", "Menjaga kelembapan"],
  },
  {
    slug: "radiant-fresh-toner",
    name: "Radiant Fresh Toner",
    brand: "Radiant",
    category: "toner",
    categoryLabel: "Toner",
    price: 89000,
    image: "/refreshing-toner-bottle-clear-minimal.jpg",
    tags: ["Centella", "Allantoin"],
    suitableSkinTypes: ["normal", "kombinasi"],
    benefits: ["Menenangkan", "Menghidrasi ringan"],
  },
  {
    slug: "radiant-shield-spf50",
    name: "Radiant Shield SPF50",
    brand: "Radiant",
    category: "sunscreen",
    categoryLabel: "Sunscreen",
    price: 129000,
    image: "/sunscreen-tube-spf50-minimal-packaging.jpg",
    tags: ["UVA/UVB Filter", "Vitamin E"],
    suitableSkinTypes: ["normal", "kombinasi", "berminyak"],
    benefits: ["Perlindungan tinggi", "Ringan"],
  },
  {
    slug: "pure-skin-ceramide-cream",
    name: "Pure Skin Ceramide Cream",
    brand: "Pure Skin",
    category: "moisturizer",
    categoryLabel: "Moisturizer",
    price: 115000,
    image: "/ceramide-moisturizer-jar-neutral-background.jpg",
    tags: ["Ceramide", "Squalane"],
    suitableSkinTypes: ["kering", "normal"],
    benefits: ["Perbaiki skin barrier", "Lembap tahan lama"],
  },
  {
    slug: "pure-skin-hydra-serum",
    name: "Pure Skin Hydra Serum",
    brand: "Pure Skin",
    category: "serum",
    categoryLabel: "Serum",
    price: 99000,
    image: "/hydrating-serum-dropper-bottle.jpg",
    tags: ["Hyaluronic Acid", "Glycerin"],
    suitableSkinTypes: ["kering", "normal", "kombinasi"],
    benefits: ["Hidrasi intens", "Kulit tampak plump"],
  },
]

export const stores = [
  {
    slug: "glow-official",
    name: "Glow Official Store",
    url: "https://example.com/glow-official",
    description: "Toko resmi produk Glow.",
    logo: "/glow-official-logo.jpg",
  },
  {
    slug: "radiant-resmi",
    name: "Radiant Resmi",
    url: "https://example.com/radiant",
    description: "Pilihan produk kurasi Radiant.",
    logo: "/radiant-logo.jpg",
  },
]
